"""
Ground-station interop, simulated without radio hardware.

The open question this module closes is not "does a radio work", it is "can
software that has never seen GistLink read what GistLink transmits". Hardware
contributes nothing to that: the answer lives entirely in the bytes. So the
frames here are generated by GistLink and then parsed by two unrelated CCSDS
libraries, plus one derandomiser written from the standard rather than copied
from :mod:`gistlink.tmframe`.

* ``spacepackets`` parses TM Transfer Frames and Space Packets, and verifies
  the Frame Error Control Field with its own CRC-16 implementation.
* ``ccsdspy``, an independent reader used for archived mission telemetry,
  parses the Space Packet stream a second time and reports structural faults.

No GistLink code decodes anything in the receive direction until the final
end-to-end test, which is explicitly labelled as the point where the library
takes over from the ground station. If these tests pass, the transport layers
are externally confirmed; the atoms inside them still need this library, which
is the documented split in RELEASE_NOTES.md.

What this does *not* cover: the Reed-Solomon codeblock. No third-party package
on PyPI implements the CCSDS RS parameters, so that layer remains verified
against the published libfec parameters and an independent construction with
``galois``, as recorded in tests/test_ccsds.py.
"""

from __future__ import annotations

import pytest

from gistlink import pack_compressed_message, unpack_compressed_stream
from gistlink import tmframe as tf
from gistlink.spacepacket import APID_MAP, SpacePacketSequenceCounter, wrap

spacepackets = pytest.importorskip("spacepackets")

from spacepackets.ccsds.spacepacket import SpacePacketHeader  # noqa: E402
from spacepackets.ccsds.tm_frame import TmTransferFrame  # noqa: E402
from spacepackets.exceptions import InvalidCrcCcitt16Error  # noqa: E402

ASM = bytes.fromhex("1acffc1d")
FRAME_LEN = 1115
WIRE_LEN = 1119

# CCSDS 131.0-B, Table 9-1. The first eight octets of the pseudo-randomiser
# sequence, quoted from the standard rather than produced by any code here.
PUBLISHED_PN_HEAD = bytes.fromhex("ff480ec09a0d70bc")


def independent_pn(length: int) -> bytes:
    """
    The CCSDS pseudo-randomiser sequence, derived from the polynomial.

    Written as an eight-bit shift register with taps at the positions given by
    h(x) = x^8 + x^7 + x^5 + x^3 + 1, all-ones initial state, most significant
    bit first. :func:`gistlink.tmframe._pn_sequence` computes the same sequence
    from the recurrence form instead, so agreement between the two is a real
    check and not a tautology.
    """
    state = 0xFF
    bits = []
    for _ in range(length * 8):
        bits.append((state >> 7) & 1)
        feedback = (
            (state & 1) ^ ((state >> 2) & 1) ^ ((state >> 4) & 1) ^ ((state >> 7) & 1)
        )
        state = ((state << 1) | feedback) & 0xFF

    out = bytearray(length)
    for i in range(length):
        value = 0
        for bit in bits[i * 8:(i + 1) * 8]:
            value = (value << 1) | bit
        out[i] = value
    return bytes(out)


PN_MASK = independent_pn(FRAME_LEN)


def receive(wire: bytes):
    """
    Do what a ground station does: find the ASM, derandomise, parse, check CRC.

    Returns one ``TmTransferFrame`` per frame, parsed entirely by
    ``spacepackets``. It raises ``InvalidCrcCcitt16Error`` on a bad FECF, so a
    frame coming back at all means its error control field checked out against
    a CRC implementation GistLink had no part in.
    """
    assert len(wire) % WIRE_LEN == 0, "wire stream is not a whole number of frames"
    frames = []
    for offset in range(0, len(wire), WIRE_LEN):
        block = wire[offset:offset + WIRE_LEN]
        assert block[:4] == ASM, f"no attached sync marker at offset {offset}"
        derandomised = bytes(a ^ b for a, b in zip(block[4:], PN_MASK))
        frames.append(TmTransferFrame.unpack(derandomised, FRAME_LEN, True))
    return frames


def extract_packets(frames):
    """
    Reassemble Space Packets across frames using the First Header Pointer.

    This is the packet extraction a receiver performs on a virtual channel:
    concatenate the data fields in frame-count order, start at the FHP the
    first frame advertises, and walk the packet length fields from there.
    """
    blob = b"".join(frame.data_field for frame in frames)
    offset = frames[0].primary_header.frame_datafield_status.first_header_pointer
    packets = []
    while offset + 6 <= len(blob):
        header = SpacePacketHeader.unpack(blob[offset:])
        total = 6 + header.data_len + 1
        if header.apid == 0x7FF or offset + total > len(blob):
            break  # idle packet or fill: end of real data
        packets.append((header, blob[offset + 6:offset + total]))
        offset += total
    return packets


def make_packet_stream(payload: bytes, msg_type: str = "DETECT", chunk: int = 900):
    counter = SpacePacketSequenceCounter()
    return b"".join(
        wrap(payload[i:i + chunk], msg_type, counter)
        for i in range(0, len(payload), chunk)
    )


def incompressible(n: int) -> bytes:
    """Deterministic high-entropy bytes, so the payload survives compression."""
    import random

    rng = random.Random(20260915)
    return bytes(rng.getrandbits(8) for _ in range(n))


class TestPseudoRandomizer:
    """The randomiser is what a receiver applies before it can see anything."""

    def test_matches_the_published_vector(self):
        assert independent_pn(8) == PUBLISHED_PN_HEAD

    def test_gistlink_randomiser_agrees(self):
        # Randomising zeros yields the sequence itself, so this compares
        # GistLink's output against a derivation it does not share.
        assert tf.apply_prng(bytes(FRAME_LEN)) == PN_MASK

    def test_the_randomiser_is_its_own_inverse(self):
        data = incompressible(FRAME_LEN)
        assert tf.apply_prng(tf.apply_prng(data)) == data


class TestSpacePacketHeaders:
    """Every APID GistLink emits, parsed by spacepackets."""

    @pytest.mark.parametrize("msg_type", sorted(APID_MAP))
    def test_header_fields(self, msg_type):
        expected_apid, expected_type = APID_MAP[msg_type]
        payload = b"payload for " + msg_type.encode()
        packet = wrap(payload, msg_type, SpacePacketSequenceCounter())

        header = SpacePacketHeader.unpack(packet)
        assert header.apid == expected_apid
        assert int(header.packet_type) == expected_type
        assert header.ccsds_version == 0
        # The length field is "octets in the data field, minus one".
        assert header.data_len == len(payload) - 1
        assert 6 + header.data_len + 1 == len(packet)

    def test_sequence_counts_advance_per_apid(self):
        counter = SpacePacketSequenceCounter()
        a1 = SpacePacketHeader.unpack(wrap(b"one", "TEXT", counter))
        b1 = SpacePacketHeader.unpack(wrap(b"two", "STATUS", counter))
        a2 = SpacePacketHeader.unpack(wrap(b"three", "TEXT", counter))

        assert (a1.seq_count, a2.seq_count) == (0, 1)
        assert b1.seq_count == 0, "counters must be per-APID, not global"


class TestCcsdspy:
    """A second, unrelated packet reader over the same bytes."""

    def stream_file(self, tmp_path, blob):
        path = tmp_path / "telemetry.bin"
        path.write_bytes(blob)
        return str(path)

    def test_reports_no_structural_faults(self, tmp_path):
        utils = pytest.importorskip("ccsdspy.utils")
        blob = make_packet_stream(incompressible(4000))
        # validate() returns a list of problems it found. Empty is the claim.
        assert utils.validate(self.stream_file(tmp_path, blob)) == []

    def test_headers_and_payloads_agree(self, tmp_path):
        utils = pytest.importorskip("ccsdspy.utils")
        payload = incompressible(2500)
        blob = make_packet_stream(payload, msg_type="STATUS", chunk=700)
        path = self.stream_file(tmp_path, blob)

        headers = utils.read_primary_headers(path)
        assert utils.count_packets(path) == 4
        assert list(headers["CCSDS_APID"]) == [APID_MAP["STATUS"][0]] * 4
        assert list(headers["CCSDS_SEQUENCE_COUNT"]) == [0, 1, 2, 3]
        assert list(headers["CCSDS_VERSION_NUMBER"]) == [0] * 4
        # 3 means "unsegmented", the only grouping GistLink uses.
        assert list(headers["CCSDS_SEQUENCE_FLAG"]) == [3] * 4

        rebuilt = b"".join(p[6:] for p in utils.split_packet_bytes(path))
        assert rebuilt == payload


class TestTmTransferFrames:
    """Frames, as a receiver sees them: sync, derandomise, check, parse."""

    def test_single_frame(self):
        packets = make_packet_stream(b"nominal telemetry")
        frames = receive(tf.encode_frames(packets, scid=42, vcid=1))

        assert len(frames) == 1
        header = frames[0].primary_header
        assert header.master_channel_id.spacecraft_id == 42
        assert header.master_channel_id.transfer_frame_version == 0
        assert header.vc_id == 1
        assert header.ocf_flag is False
        assert len(frames[0].data_field) == tf.FRAME_DATA_SIZE

    def test_frame_counts_advance(self):
        wire = tf.encode_frames(make_packet_stream(incompressible(9000)), scid=9)
        frames = receive(wire)

        assert len(frames) > 1
        counts = [f.primary_header.vc_frame_count for f in frames]
        assert counts == list(range(len(frames)))
        master = [f.primary_header.master_ch_frame_count for f in frames]
        assert master == list(range(len(frames)))

    def test_packet_mode_first_header_pointer(self):
        wire = tf.encode_frames(
            make_packet_stream(incompressible(9000)), scid=9, mode=tf.MODE_PACKET
        )
        frames = receive(wire)
        status = [f.primary_header.frame_datafield_status for f in frames]

        assert all(s.sync_flag is False for s in status), "packet mode must be sync=0"
        assert status[0].first_header_pointer == 0
        for s in status:
            # A pointer into the data field, or the reserved "no packet starts
            # here" value. Anything else routes the receiver into noise.
            assert s.first_header_pointer < tf.FRAME_DATA_SIZE or (
                s.first_header_pointer == tf.FHP_NO_PACKET_START
            )

    def test_vca_mode_declares_no_packets(self):
        wire = tf.encode_frames(incompressible(3000), scid=7, vcid=3, mode=tf.MODE_VCA)
        frames = receive(wire)

        assert len(frames) == 3
        for frame in frames:
            status = frame.primary_header.frame_datafield_status
            assert status.sync_flag is True, "VCA mode must set the sync flag"
            assert frame.primary_header.vc_id == 3

    def test_corruption_is_caught_by_the_third_party_crc(self):
        wire = bytearray(tf.encode_frames(make_packet_stream(b"telemetry"), scid=1))
        wire[600] ^= 0x01

        with pytest.raises(InvalidCrcCcitt16Error):
            receive(bytes(wire))

    def test_error_control_field_is_present_and_checked(self):
        frames = receive(tf.encode_frames(make_packet_stream(b"telemetry"), scid=1))
        assert frames[0].frame_error_control is not None
        assert len(frames[0].frame_error_control) == tf.FECF_SIZE


class TestEndToEnd:
    """The full chain, with the handover to GistLink made explicit."""

    def test_ground_station_recovers_the_payload(self):
        message = incompressible(6000)
        stream = pack_compressed_message(message, "BINARY")
        wire = tf.encode_frames(
            make_packet_stream(stream), scid=42, vcid=1, mode=tf.MODE_PACKET
        )

        # Everything to here is third-party parsing.
        packets = extract_packets(receive(wire))
        assert [h.seq_count for h, _ in packets] == list(range(len(packets)))
        assert {h.apid for h, _ in packets} == {APID_MAP["DETECT"][0]}
        recovered = b"".join(payload for _, payload in packets)
        assert recovered == stream, "transport layers did not deliver the SDU intact"

        # Only now does GistLink decode its own atoms, which is exactly the
        # boundary RELEASE_NOTES.md describes: transport interop is free,
        # payload interop needs this library.
        assert unpack_compressed_stream(recovered)["data"] == message

    def test_survives_a_frame_sized_payload_boundary(self):
        # A payload that lands exactly on a frame boundary is where off-by-one
        # errors in the fill and pointer logic show up.
        stream = incompressible(tf.FRAME_DATA_SIZE * 2 - 6)
        wire = tf.encode_frames(
            make_packet_stream(stream, chunk=len(stream)),
            scid=3,
            mode=tf.MODE_PACKET,
        )
        packets = extract_packets(receive(wire))
        assert b"".join(p for _, p in packets) == stream
