"""
Type stubs for astral_compress Rust extension.
This provides type hints for Pylance and other type checkers.
"""


def compress_telemetry(data: bytes, channels: int) -> bytes: ...
def decompress_telemetry(payload_bytes: bytes, original_length: int, channels: int) -> bytes: ...


def compress_binary_float(data: bytes) -> bytes: ...
def decompress_binary_float(payload_bytes: bytes, original_length: int) -> bytes: ...


def compress_text(data: bytes) -> bytes: ...
def decompress_text(data: bytes) -> bytes: ...
